# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dxf_marking_form.ui'
#
# Created by: PyQt5 UI code generator 5.9
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(963, 692)
        MainWindow.setMinimumSize(QtCore.QSize(800, 600))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.clotheListWidget = QtWidgets.QListWidget(self.centralwidget)
        self.clotheListWidget.setGeometry(QtCore.QRect(10, 10, 161, 401))
        self.clotheListWidget.setObjectName("clotheListWidget")
        self.partListWidget = QtWidgets.QListWidget(self.centralwidget)
        self.partListWidget.setGeometry(QtCore.QRect(180, 10, 161, 401))
        self.partListWidget.setObjectName("partListWidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(350, 310, 331, 16))
        self.frame.setFrameShape(QtWidgets.QFrame.HLine)
        self.frame.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frame.setObjectName("frame")
        self.buttonLoad1 = QtWidgets.QPushButton(self.centralwidget)
        self.buttonLoad1.setGeometry(QtCore.QRect(350, 10, 75, 23))
        self.buttonLoad1.setObjectName("buttonLoad1")
        self.buttonLoad2 = QtWidgets.QPushButton(self.centralwidget)
        self.buttonLoad2.setGeometry(QtCore.QRect(350, 320, 75, 23))
        self.buttonLoad2.setObjectName("buttonLoad2")
        self.segmentList1 = QtWidgets.QComboBox(self.centralwidget)
        self.segmentList1.setGeometry(QtCore.QRect(350, 40, 71, 22))
        self.segmentList1.setObjectName("segmentList1")
        self.segmentList2 = QtWidgets.QComboBox(self.centralwidget)
        self.segmentList2.setGeometry(QtCore.QRect(350, 350, 71, 22))
        self.segmentList2.setObjectName("segmentList2")
        self.addSegment1 = QtWidgets.QPushButton(self.centralwidget)
        self.addSegment1.setGeometry(QtCore.QRect(350, 70, 61, 23))
        self.addSegment1.setObjectName("addSegment1")
        self.addSegment2 = QtWidgets.QPushButton(self.centralwidget)
        self.addSegment2.setGeometry(QtCore.QRect(350, 380, 61, 23))
        self.addSegment2.setObjectName("addSegment2")
        self.loadJoint = QtWidgets.QPushButton(self.centralwidget)
        self.loadJoint.setGeometry(QtCore.QRect(257, 420, 41, 23))
        self.loadJoint.setObjectName("loadJoint")
        self.storeJoint = QtWidgets.QPushButton(self.centralwidget)
        self.storeJoint.setGeometry(QtCore.QRect(213, 420, 41, 23))
        self.storeJoint.setObjectName("storeJoint")
        self.jointList = QtWidgets.QComboBox(self.centralwidget)
        self.jointList.setGeometry(QtCore.QRect(55, 421, 111, 22))
        self.jointList.setObjectName("jointList")
        self.addJoint = QtWidgets.QPushButton(self.centralwidget)
        self.addJoint.setGeometry(QtCore.QRect(10, 420, 41, 23))
        self.addJoint.setObjectName("addJoint")
        self.removeJoint = QtWidgets.QPushButton(self.centralwidget)
        self.removeJoint.setGeometry(QtCore.QRect(300, 420, 41, 23))
        self.removeJoint.setObjectName("removeJoint")
        self.removeSegment1 = QtWidgets.QPushButton(self.centralwidget)
        self.removeSegment1.setGeometry(QtCore.QRect(350, 100, 61, 23))
        self.removeSegment1.setObjectName("removeSegment1")
        self.removeSegment2 = QtWidgets.QPushButton(self.centralwidget)
        self.removeSegment2.setGeometry(QtCore.QRect(350, 410, 61, 23))
        self.removeSegment2.setObjectName("removeSegment2")
        self.invertJoint = QtWidgets.QPushButton(self.centralwidget)
        self.invertJoint.setGeometry(QtCore.QRect(170, 420, 41, 23))
        self.invertJoint.setObjectName("invertJoint")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 963, 21))
        self.menubar.setObjectName("menubar")
        self.menuTest = QtWidgets.QMenu(self.menubar)
        self.menuTest.setObjectName("menuTest")
        self.menuData_processing = QtWidgets.QMenu(self.menubar)
        self.menuData_processing.setObjectName("menuData_processing")
        self.menuParts = QtWidgets.QMenu(self.menubar)
        self.menuParts.setObjectName("menuParts")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionOpen_project = QtWidgets.QAction(MainWindow)
        self.actionOpen_project.setObjectName("actionOpen_project")
        self.actionSave_project = QtWidgets.QAction(MainWindow)
        self.actionSave_project.setObjectName("actionSave_project")
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.actionLoad_DXF_file = QtWidgets.QAction(MainWindow)
        self.actionLoad_DXF_file.setObjectName("actionLoad_DXF_file")
        self.actionNew_project = QtWidgets.QAction(MainWindow)
        self.actionNew_project.setObjectName("actionNew_project")
        self.actionAdd_new_file = QtWidgets.QAction(MainWindow)
        self.actionAdd_new_file.setObjectName("actionAdd_new_file")
        self.actionRename_file = QtWidgets.QAction(MainWindow)
        self.actionRename_file.setObjectName("actionRename_file")
        self.actionDelete_file = QtWidgets.QAction(MainWindow)
        self.actionDelete_file.setObjectName("actionDelete_file")
        self.actionMove_up_file = QtWidgets.QAction(MainWindow)
        self.actionMove_up_file.setObjectName("actionMove_up_file")
        self.actionMove_down_file = QtWidgets.QAction(MainWindow)
        self.actionMove_down_file.setObjectName("actionMove_down_file")
        self.actionRename_part = QtWidgets.QAction(MainWindow)
        self.actionRename_part.setObjectName("actionRename_part")
        self.actionMove_part_up = QtWidgets.QAction(MainWindow)
        self.actionMove_part_up.setObjectName("actionMove_part_up")
        self.actionMove_part_down = QtWidgets.QAction(MainWindow)
        self.actionMove_part_down.setObjectName("actionMove_part_down")
        self.actionChange_parent_item = QtWidgets.QAction(MainWindow)
        self.actionChange_parent_item.setObjectName("actionChange_parent_item")
        self.actionDuplicate_part = QtWidgets.QAction(MainWindow)
        self.actionDuplicate_part.setObjectName("actionDuplicate_part")
        self.actionDelete_part = QtWidgets.QAction(MainWindow)
        self.actionDelete_part.setObjectName("actionDelete_part")
        self.actionInverse_part = QtWidgets.QAction(MainWindow)
        self.actionInverse_part.setObjectName("actionInverse_part")
        self.menuTest.addAction(self.actionNew_project)
        self.menuTest.addAction(self.actionOpen_project)
        self.menuTest.addAction(self.actionSave_project)
        self.menuTest.addSeparator()
        self.menuTest.addAction(self.actionExit)
        self.menuData_processing.addAction(self.actionLoad_DXF_file)
        self.menuData_processing.addAction(self.actionAdd_new_file)
        self.menuData_processing.addAction(self.actionRename_file)
        self.menuData_processing.addAction(self.actionDelete_file)
        self.menuData_processing.addAction(self.actionMove_up_file)
        self.menuData_processing.addAction(self.actionMove_down_file)
        self.menuParts.addAction(self.actionRename_part)
        self.menuParts.addAction(self.actionMove_part_up)
        self.menuParts.addAction(self.actionMove_part_down)
        self.menuParts.addAction(self.actionChange_parent_item)
        self.menuParts.addAction(self.actionDuplicate_part)
        self.menuParts.addAction(self.actionDelete_part)
        self.menuParts.addAction(self.actionInverse_part)
        self.menubar.addAction(self.menuTest.menuAction())
        self.menubar.addAction(self.menuData_processing.menuAction())
        self.menubar.addAction(self.menuParts.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Smart clothing architecture simulator"))
        self.buttonLoad1.setText(_translate("MainWindow", "Load"))
        self.buttonLoad2.setText(_translate("MainWindow", "Load"))
        self.addSegment1.setText(_translate("MainWindow", "+Segment"))
        self.addSegment2.setText(_translate("MainWindow", "+Segment"))
        self.loadJoint.setText(_translate("MainWindow", "Joint >"))
        self.storeJoint.setText(_translate("MainWindow", "< Joint"))
        self.addJoint.setText(_translate("MainWindow", "+ Joint"))
        self.removeJoint.setText(_translate("MainWindow", "- Joint"))
        self.removeSegment1.setText(_translate("MainWindow", "-Segment"))
        self.removeSegment2.setText(_translate("MainWindow", "-Segment"))
        self.invertJoint.setText(_translate("MainWindow", "Inv"))
        self.menuTest.setTitle(_translate("MainWindow", "File"))
        self.menuData_processing.setTitle(_translate("MainWindow", "Clothing items"))
        self.menuParts.setTitle(_translate("MainWindow", "Parts"))
        self.actionOpen_project.setText(_translate("MainWindow", "Open project"))
        self.actionSave_project.setText(_translate("MainWindow", "Save project"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))
        self.actionLoad_DXF_file.setText(_translate("MainWindow", "Load item from DXF file"))
        self.actionNew_project.setText(_translate("MainWindow", "New project"))
        self.actionAdd_new_file.setText(_translate("MainWindow", "Add new item +"))
        self.actionRename_file.setText(_translate("MainWindow", "Rename item ~"))
        self.actionDelete_file.setText(_translate("MainWindow", "Delete item -"))
        self.actionMove_up_file.setText(_translate("MainWindow", "Move item up /\\"))
        self.actionMove_down_file.setText(_translate("MainWindow", "Move item down \\/"))
        self.actionRename_part.setText(_translate("MainWindow", "Rename part ~"))
        self.actionMove_part_up.setText(_translate("MainWindow", "Move part up /\\"))
        self.actionMove_part_down.setText(_translate("MainWindow", "Move part down \\/"))
        self.actionChange_parent_item.setText(_translate("MainWindow", "Change parent item ?"))
        self.actionDuplicate_part.setText(_translate("MainWindow", "Duplicate part x2"))
        self.actionDelete_part.setText(_translate("MainWindow", "Delete part -"))
        self.actionInverse_part.setText(_translate("MainWindow", "Inverse part <-->"))

